MagiCircles/BanGDream

bang/migrations/0004_auto_20170407_1901.py
bang/models.py

i also increased the field length to 500 chars, just in case

use skill_details as description when available

---

api/views.py
bang_project/urls.py

lifted from SIT, they make DB updating quite a bit easier...

add /cardids/ and /memberids/ to API

---

.gitignore
bang/forms.py
bang/magicollections.py

Close #47 
- Adds Boost Member sorting to events
- Adds Boost Attribute sorting to events

Events boost member & attribute filtering

---

bang/forms.py
bang/magicollections.py

Close #14 
- Change default ordering to id
- Create Ordering by id, named Band

Change Character Default Ordering

---

bang/forms.py
bang/magicollections.py

- Made Featured_Member field in forms and added it to the sidebar so that users can search for a specific member within all the gachas
- Added i_attribute to the sidebar

Added Featured Member & Attribute Filters

---

bang/magicollections.py
bang/templates/pages/live2dviewer.html
bang/views.py

I figured out how to reproduce the script loading issues from last night and hopefully fixed them here. I've also fixed the screenshot-with-background button.
Depends on https://github.com/MagiCircles/BanGDream-Static/pull/2.

Live2D: fix all the cors bugs

---

bang/models.py

Thank Roselia for making harder songs in the game
Changes: Changed MaxValueValidator to 29 instead of 28

Change max song difficulty to 29

---

bang/forms.py
bang/models.py

this adds the Special difficulty (will be used starting with the event tomorrow) to Song and PlayedSong. 
It also bumps the max difficulty to 50 just in case.
Needs https://github.com/MagiCircles/BanGDream-Static/pull/9

Add special difficulty category

---

bang/models.py

Change the name of Band Battle to VS Live

Bye Bye Band Battles, and Hello VS Lives!

---

bang/settings.py

Since today's Roselia fanmeet is the VA's last event with Roselia, it feels only right that we give her a farewell week too!
+ Adds Thank you Ake-san tag, available from NOW to 9/25 midnight UTC

Thank you Ake-san

---

bang/management/commands/generate_settings.py
bang/settings.py

This reverts commit 0214e92245cd0bb98f4c5c7788c7f56eb8775a14.
Static Files: https://github.com/MagiCircles/BanGDream-Static/pull/13

Revert "AglowPa (#147)"

---

bang/settings.py

Pretty simple stuff. Added start-time since we're wanting to pre-announce the event (and this will allow us to not have to be active during the start time either, which is nice)
Have a Happy CosParty! 🎉

CosParty18 tag

---

bang/management/commands/generate_settings.py
bang/settings.py

In celebration of Hello, Happy World!'s second band story, let's give our site a HaroHapi coating!
Static Files: https://github.com/MagiCircles/BanGDream-Static/pull/14

HaroHapiPartyYay!

---

bang/models.py

Change TW event time:
Start at 15:00 (Asia/Taipei)
End at 20:59 (Asia/Taipei)
close #193

Change TW End/Start Event Time

---

bang/magicollections.py

Adds song_alt_cover field to songs IF there are assets tagged with #Album cover
close #198

Alt Covers

---

bang/magicollections.py

+ Alt Covers now show EVERY version of an asset
+ Images in field now link to high-res directly instead of asset
+ Commented code for clarity

Alt Cover Adjustment

---

bang/models.py

Add Member field+filter for Titles

---

bang/magicollections.py
bang/management/commands/generate_settings.py
bang/models.py
bang/templates/items/memberItem.html

plus stuff to support this change, including:
- can specify member IDs on creation
- extending member page size
- allowing members to have no cards without breaking site
Depends on https://github.com/MagiCircles/BanGDream-Static/pull/22

add RAS to band list

---

api/views.py
bang/magicollections.py
bang/models.py

For 4.0, based on hopefully accurate livestream TLs

Add new skill types

---

bang/forms.py
bang/magicollections.py
bang/models.py

When someone has a Stage Name, the name and japanese_name fields will be filled in with their stage name, and their offstage name will be put in the alt_name and japanese_alt_name fields.
Third and Junior 2nd School Years were added for Season 2 and PAREO.
🔧 If possible, any name translations for RAS should be moved to alt_name.

🗄🌐🔧  Add Stage Names to Member + Add School Years

---

bang/forms.py
bang/magicollections.py
bang/models.py
bang/templates/items/songItem.html

Adds functionality to differentiate FULL versions of songs from other songs.
Static Dependency: https://github.com/MagiCircles/BanGDream-Static/pull/23

🗄️🎨🌐Add FULL ver. of songs
